In [3]:
import numpy as np
ar1=np.arange(13)

In [4]:
ar1
len(ar1)

13

In [5]:
reshaped_array=ar1.reshape(1,13)
reshaped_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [10]:
# identity matrix can be created using 2 fun
# eye()-->used to define both user deffined rows and col
# identity-->used to define same no of rows and col
# syntax-->np.eye(3,4) 3 rows,4col
# syntax-->np.identiy(3) 3 rows 3 col
np.eye(3,4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [11]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [13]:
ar2=np.arange(25)

In [14]:
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
#to perform multi dimensional slicing
ar2=np.arange(25).reshape(5,5)

In [16]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [17]:
ar2.shape

(5, 5)

In [18]:
# ar2[row:step,col:step
# ar2[rows start:row end,col start: col end]
ar2[0:4]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [21]:
ar2[-3:-1,-3:-1]

array([[12, 13],
       [17, 18]])

### 

In [22]:
ar3=np.arange(50).reshape(5,10)

In [23]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [24]:
#linshape
np.sum(ar3)

1225

In [25]:
ar3.sum(axis=0)
#to add based on column wise

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [26]:
ar3.sum(axis=1)
#to add based on row wise

array([ 45, 145, 245, 345, 445])

In [27]:
# mean-->avg
# median-->middle value
# mode-->repeated value
# variance-->median/total no of ele
# std-->square root of variance

np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [28]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [29]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [30]:
# linspace
# it is used to print evenly separated point
# between 2 range of vaues
# linspace(start,end,no of parts)
np.linspace(1,10,4,dtype=int)

array([ 1,  4,  7, 10])

In [31]:
np.linspace(1,10,4,dtype=complex)

array([ 1.+0.j,  4.+0.j,  7.+0.j, 10.+0.j])

In [32]:
np.linspace(1,10,4,dtype=float)

array([ 1.,  4.,  7., 10.])

In [33]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [34]:
np.linspace(12,30,12,retstep=False)

array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
       20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
       28.36363636, 30.        ])

In [35]:
# random module
# to generate random number between range
# np.random.randint(start,end)
# np.random.randint(start,end,no of ele)
np.random.randint(50)

17

In [36]:
np.random.randint(20,50,3)

array([41, 43, 25])

In [37]:
# rand()-->
# to get randomly generated values from 0 to 1 based on uniform distribution
np.random.rand(4)

array([0.22969114, 0.46884206, 0.42803289, 0.40083032])

In [38]:
np.random.rand(3,4)

array([[0.46666829, 0.76994315, 0.28195355, 0.95000189],
       [0.51607519, 0.12600904, 0.79110289, 0.69153603],
       [0.18927869, 0.42757899, 0.6187103 , 0.83045311]])

In [39]:
# to get randomly generated values from 0 to 1 based on nomalised distribution
np.random.randn(4)

array([ 1.57969164, -0.070067  ,  1.02484546, -0.8379118 ])

In [40]:
np.random.randn(5,4)

array([[-1.52550371, -0.74633436, -1.30888339, -0.48841692],
       [ 0.75024393,  0.61910072,  0.39035654, -2.55757981],
       [-1.03507032,  0.81197301,  0.88273522, -0.74565544],
       [-1.9888847 ,  0.29553682,  0.29837631, -0.20086384],
       [ 0.19809926, -1.74348297,  0.17597991, -0.92197107]])

In [41]:
ar3.min()

0

In [42]:
ar3.max()

49

In [44]:
#to find index of  value
l1=[56,89,90,67,45]
print(l1.index(67))

3


In [45]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [46]:
l1=[56,89,90,67,45]
np1=np.array(l1)
#argmin-->to find min value index pos in array
print(np1.argmin())
#argmax-->to find max value index pos in array
print(np1.argmax())

4
2


In [47]:
np1

array([56, 89, 90, 67, 45])

In [48]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [49]:
np.sin(np1)

array([-0.521551  ,  0.86006941,  0.89399666, -0.85551998,  0.85090352])

In [50]:
np.cos(np1)

array([ 0.85322011,  0.51017704, -0.44807362, -0.5177698 ,  0.52532199])

In [51]:
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [53]:
1 /np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [54]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [55]:
1/np.tan(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [56]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
# (1x4)+(2x5)+(3x6)=4+10+18=>32
sum(np2*np3)

32

In [58]:
np.dot(np2,np3)

32

In [63]:
np2=np.array([1,2,3,9])
#np3=np.array([4,5,6])
#we will take 4th ele in np3 aas 1 by default
np3=np.array([4,5,6,1])
sum(np2*np3)

41

In [64]:
np.dot(np2,np3)

41

In [66]:
fname=np.array(["sid","fn1","fn2"])
lname=np.array(["t","ln1","ln2"])
#fname.tostring()

In [70]:
np2=np.array([1,2,3,8,3,5,9])
np3=np.array([4,5,6])
len1=len(np2)
len2=len(np3)
diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
np.sum((np2*np3))

57

In [79]:
np1=np.array([1,34,56,78,np.nan,np.nan])

In [80]:
#to print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [82]:
#to eliminate nan values
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [1]:
#pandas
import pandas as pd
#pandas is defined as an open source library that provides a high performance data manipulation in python
#data analysis requires a lot of process such as restructuring,cleaning,manipulating etc...we prefer pandas to perform this above function coz it is fast,simple than other tools
#pandas is built on numpy so numpy is required for operating pandas




In [2]:
#pandas series
# pandas series is a data structure with one dimensional labelled array
# it is a primary building block of dataframe,making its rows and columns


In [5]:
import numpy as np
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100,'b':200,'c':300}


In [7]:
#syntax-->pandas.Series(data=None,index=None,dtype=None,name=None,copy=True or False)
#eg 1
import pandas as pd
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [9]:
pd.Series(d)

a    100
b    200
c    300
dtype: int64

In [10]:
type(pd.Series(my_data))

pandas.core.series.Series

In [12]:
#series with tables
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [13]:
      #or
pd.Series(my_data,labels)    

a    10
b    20
c    30
dtype: int64

In [15]:
pd.Series(data=[print,sum,len])

0    <built-in function print>
1      <built-in function sum>
2      <built-in function len>
dtype: object

In [16]:
pd.Series(data=[print(),sum,len])

0                       None
1    <built-in function sum>
2    <built-in function len>
dtype: object

In [20]:
class profile:
#@property
    def display(self):
        print("my name ")
p=profile()
p.display()

my name 


In [22]:
def greet():
    return "gud mrng"
print(greet())


gud mrng


In [29]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner()
@decor
def greet():
    return "gud mrng"
print(greet())


TypeError: 'str' object is not callable

In [32]:
ser1=pd.Series([1,2,3,4,5],['USA','india','canada','UK','egypt'])

# 

In [33]:
ser1

USA       1
india     2
canada    3
UK        4
egypt     5
dtype: int64

In [38]:
ser1['canada']

3

In [37]:
#access values using indexing
ser1[4]

5

In [39]:
ser1['india']

2

In [40]:
ser1[2]

3

In [41]:
ser1[0:3]

USA       1
india     2
canada    3
dtype: int64

In [43]:
ser2=pd.Series([5,6,7,8],['USA','canada','UK','egypt'])
ser1+ser2

UK        11.0
USA        6.0
canada     9.0
egypt     13.0
india      NaN
dtype: float64

In [44]:
ser1=pd.Series([1,2,3,4,5],['USA','india','canada','UK','egypt'])
ser2=pd.Series([5,6,8],['canada','UK','egypt'])
ser1+ser2

UK        10.0
USA        NaN
canada     8.0
egypt     13.0
india      NaN
dtype: float64

In [46]:
#to create a new data in series

ser2

canada    5
UK        6
egypt     8
dtype: int64

In [47]:
ser2['china']='duplicate'

In [48]:
ser2

canada            5
UK                6
egypt             8
china     duplicate
dtype: object

In [52]:
#data frame
#pd.DataFrame(datas,row_label,col_label)

In [53]:
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0  0.819130  1.420824 -1.574245 -0.365248
1 -0.441826 -0.724536  1.004190  0.892504
2  0.091437  0.526706  0.176922 -1.625459
3 -0.839633 -0.701228 -0.095789  0.127554
4  1.521416 -0.405155 -0.325216 -0.360579

In [54]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [63]:
df

col1  col2  col3
0     1     3     5
1     2     4     6
2     7     8     9

In [65]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [67]:
df.T

0  1  2
col1  1  2  7
col2  3  4  8
col3  5  6  9

In [66]:
#to convert dictionary to DataFrame
d={"col1":[1,2,7],"col2":[3,4,8],"col3":[5,6,9]}
d

{'col1': [1, 2, 7], 'col2': [3, 4, 8], 'col3': [5, 6, 9]}

In [60]:
df=pd.DataFrame(data=d)

In [61]:
df

col1  col2  col3
0     1     3     5
1     2     4     6
2     7     8     9

In [62]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [68]:
df.T

0  1  2
col1  1  2  7
col2  3  4  8
col3  5  6  9

In [95]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [70]:
df.T

A         B         C         D         E
W -1.519732  0.034486  1.457589 -0.917046 -0.771942
X -1.272306 -0.963135 -0.103719  0.365920 -0.187846
Y -0.064729  0.200976 -1.340191  0.387603  1.041060
Z  0.208066  0.986364 -0.463638  0.287696  0.686632

In [72]:
df.index#rows

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

df.columns #shows columns

In [73]:
df.columns #shows columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [74]:
type(df)

pandas.core.frame.DataFrame

In [75]:
df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [77]:
#to get information aboutndata types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [79]:
df.values

array([[-1.51973191, -1.27230619, -0.06472948,  0.20806636],
       [ 0.03448592, -0.9631355 ,  0.20097602,  0.9863636 ],
       [ 1.45758875, -0.10371925, -1.34019142, -0.46363773],
       [-0.91704626,  0.36591953,  0.38760322,  0.28769578],
       [-0.77194154, -0.18784573,  1.04105995,  0.68663165]])

In [80]:
df.axes

[Index(['A', 'B', 'C', 'D', 'E'], dtype='object'),
 Index(['W', 'X', 'Y', 'Z'], dtype='object')]

In [81]:
df.ndim

2

In [82]:
df.size

20

In [85]:
# to access specific column in df
df

W         X         Y         Z
A -1.519732 -1.272306 -0.064729  0.208066
B  0.034486 -0.963135  0.200976  0.986364
C  1.457589 -0.103719 -1.340191 -0.463638
D -0.917046  0.365920  0.387603  0.287696
E -0.771942 -0.187846  1.041060  0.686632

In [87]:
df['W']

A   -1.519732
B    0.034486
C    1.457589
D   -0.917046
E   -0.771942
Name: W, dtype: float64

In [91]:
type(df['W'])

pandas.core.series.Series

In [93]:
df

W         X         Y         Z
A -1.519732 -1.272306 -0.064729  0.208066
B  0.034486 -0.963135  0.200976  0.986364
C  1.457589 -0.103719 -1.340191 -0.463638
D -0.917046  0.365920  0.387603  0.287696
E -0.771942 -0.187846  1.041060  0.686632

In [99]:
# to create new columns
df['new']=df['W']+df['Y']

In [100]:
df.drop('new',axis=1)

W         X         Y         Z
A  0.108130  2.159301  0.022184 -1.647963
B  1.136263  0.210905  2.139979 -0.570020
C  0.095068 -0.887207 -0.399384  0.409068
D  0.120921 -2.142679 -0.894933 -0.489635
E -0.883140  0.043439 -0.111967 -0.275418

In [101]:
df.drop('new',axis=1,inplace=True)

In [102]:
df

W         X         Y         Z
A  0.108130  2.159301  0.022184 -1.647963
B  1.136263  0.210905  2.139979 -0.570020
C  0.095068 -0.887207 -0.399384  0.409068
D  0.120921 -2.142679 -0.894933 -0.489635
E -0.883140  0.043439 -0.111967 -0.275418

In [ ]:
#to access rows