In [ ]:
pip list


Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.3
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.6.0
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bi

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import numpy
l1=[1,2,3,4,5]
s={5,6,7,8,9}
d=(1,3,5,7,)
arr=numpy.array(l1)
arr2=numpy.array(s)
arr3=numpy.array(d)

In [ ]:
import numpy as np

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
class c1:
  name="sindhu"
  age=20

obj=c1()
print(obj.name)
print(obj)

sindhu


In [ ]:
t1="hello"
ar1=numpy.array(t1)
ar1.dtype

dtype('<U5')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
type(list(arr))

list

In [ ]:
s={1,2,3}

In [ ]:
list(s)

[1, 2, 3]

In [ ]:
tuple(s)

(1, 2, 3)

In [ ]:
l=[1,2,3]

In [ ]:
arr=[1,2,3]

In [ ]:
arr

[1, 2, 3]

In [ ]:
arr*2

[1, 2, 3, 1, 2, 3]

In [ ]:
arr

[1, 2, 3]

In [ ]:
arr=[1,2,3]

In [ ]:
arr*2

[1, 2, 3, 1, 2, 3]

In [ ]:
ar2=[1,2,3.45,89,2]
np_ar=np.array(ar2)

In [ ]:
np_ar

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  ])

In [ ]:
new_ar=np.append(np_ar,78)
new_ar

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  , 78.  ])

In [ ]:
#to add multiple values
new_ar=np.append(np_ar,[56,33,35])
new_ar

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  , 56.  , 33.  , 35.  ])

In [ ]:
#insert
#based on index value to add ele into array
#np.insert(array_to_be_modified,index position,value)
new_ar=np.insert(np_ar,2,123)
new_ar

array([  1.  ,   2.  , 123.  ,   3.45,  89.  ,   2.  ])

In [ ]:
#insert multiple values into array
#np.insert(array_to_be_modified,index position,values in list or tuple)
new_ar=np.insert(np_ar,5,(345,567))
new_ar

array([  1.  ,   2.  ,   3.45,  89.  ,   2.  , 345.  , 567.  ])

In [ ]:
#delete ele from an array
nr=np.delete(np_ar,np.where(np_ar==2))
nr

array([ 1.  ,  3.45, 89.  ])

In [ ]:
nr=np.delete(np_ar,np.where(np_ar==3.0))
nr

array([ 1.  ,  2.  ,  3.45, 89.  ,  2.  ])

In [ ]:
nr=np.delete(np_ar,np.where(np_ar==3.45))
nr

array([ 1.,  2., 89.,  2.])

In [ ]:
#to del no of values in array
nr=np.setdiff1d(np_ar,[5.0,3.45])
nr

array([ 1.,  2., 89.])

In [ ]:
#to delete based on index pos
nr=np.delete(np_ar,0)
nr

array([ 2.  ,  3.45, 89.  ,  2.  ])

In [ ]:
#filter in numpy array
new_ar<30

array([ True,  True,  True, False,  True, False, False])

In [ ]:
new_ar[new_ar<30]

array([1.  , 2.  , 3.45, 2.  ])

In [ ]:
#to print values <20 and >50
#for and operation using &
#for or op using |
(new_ar>20) & (new_ar<50)


array([False, False, False, False, False, False, False])

In [ ]:
new_ar=[(new_ar>20)&(new_ar<50)]

In [ ]:
#to replace value in array
new_ar[new_ar==345]=56

In [ ]:
new_ar

[56]

In [ ]:
#to create 1d array full of 0
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
#to create 2d array full of 0
#syntax=np.zeros([no of rows,no of col])
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [ ]:
#to create array full of 1
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
new_ar

[array([False, False, False, False, False, False, False])]

In [ ]:
#to create 2d array full of 1
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#type convert ele in array
#to find numpy data type of ele present in array-->dtype
#type(np_ar)
np_ar.dtype

dtype('float64')

In [ ]:
#we can convert values in numpy array into various bits
#they are
#int8,int16,int32,int64
#float16,float32,float64
#complex64,complex128
#unit16,unit32

np_ar=np.zeros([2,4],dtype='int16')
np_ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [ ]:
np_ar=np.zeros([2,4],dtype='uint32')
np_ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint32)

In [ ]:
np.int16(np_ar)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)